"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var build_1 = require("./tools/gulp/build");
exports.default = build_1.build;
var build_2 = require("./tools/gulp/build");
exports.build = build_2.build;
var typescript_1 = require("./tools/gulp/typescript");
exports.compileAll = typescript_1.compileAll;
exports.compileCJS = typescript_1.compileCJS;
exports.compileESM2015 = typescript_1.compileESM2015;
exports.compileESM5 = typescript_1.compileESM5;
